"""Ablations: drop feature blocks / the scaler and see what happens.

    python scripts/run_ablations.py

The feature blocks are contiguous columns (MFCC 0:40, chroma 40:52, mel 52:180)
so I just slice the cached matrix instead of re-extracting. Each variant is run
on both splits since what helps on the random split doesn't always help on new
speakers.

Writes reports/ablations.md and reports/ablations.json.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

from speech_emotion.dataset import OBSERVED_EMOTIONS, load_dataset
from speech_emotion.features import N_CHROMA, N_MEL, N_MFCC
from speech_emotion.train import RANDOM_STATE, build_model, split_data

MFCC = slice(0, N_MFCC)
CHROMA = slice(N_MFCC, N_MFCC + N_CHROMA)
MEL = slice(N_MFCC + N_CHROMA, N_MFCC + N_CHROMA + N_MEL)

VARIANTS: list[tuple[str, list[slice], bool]] = [
    ("MFCC + chroma + mel (full)", [MFCC, CHROMA, MEL], True),
    ("MFCC only",                  [MFCC],              True),
    ("Chroma only",                [CHROMA],            True),
    ("Mel only",                   [MEL],               True),
    ("MFCC + chroma",              [MFCC, CHROMA],      True),
    ("MFCC + mel",                 [MFCC, MEL],         True),
    ("Chroma + mel",               [CHROMA, MEL],       True),
    ("Full, no StandardScaler",    [MFCC, CHROMA, MEL], False),
]


def evaluate(X, y, groups, blocks, scale, strategy):
    Xs = np.hstack([X[:, b] for b in blocks])
    X_train, X_test, y_train, y_test = split_data(Xs, y, groups, strategy=strategy)
    model = build_model(scale=scale).fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return (accuracy_score(y_test, y_pred),
            f1_score(y_test, y_pred, average="macro"),
            Xs.shape[1])


def main() -> int:
    X, y, groups = load_dataset(REPO_ROOT / "data" / "ravdess", OBSERVED_EMOTIONS,
                                cache_path=REPO_ROOT / "data" / "features_cache.npz",
                                verbose=False)
    print(f"{X.shape[0]} clips, {X.shape[1]} features, "
          f"{len(OBSERVED_EMOTIONS)} classes\n")

    rows = []
    header = f"{'variant':<28} {'dims':>5} {'random':>9} {'speaker':>9} {'gap':>7}"
    print(header)
    print("-" * len(header))

    for name, blocks, scale in VARIANTS:
        acc_r, f1_r, dims = evaluate(X, y, groups, blocks, scale, "random")
        acc_s, f1_s, _ = evaluate(X, y, groups, blocks, scale, "speaker")
        rows.append({"variant": name, "n_features": dims, "scaler": scale,
                     "random_accuracy": acc_r, "random_macro_f1": f1_r,
                     "speaker_accuracy": acc_s, "speaker_macro_f1": f1_s,
                     "gap_pp": (acc_r - acc_s) * 100})
        print(f"{name:<28} {dims:>5} {acc_r:>8.2%} {acc_s:>9.2%} "
              f"{(acc_r - acc_s) * 100:>6.1f}p")

    out_json = REPO_ROOT / "reports" / "ablations.json"
    out_json.write_text(json.dumps(
        {"classes": OBSERVED_EMOTIONS, "n_clips": int(X.shape[0]),
         "random_state": RANDOM_STATE, "results": rows}, indent=2) + "\n")

    lines = ["# Ablation study", "",
             f"4-class subset ({', '.join(OBSERVED_EMOTIONS)}), {X.shape[0]} clips, "
             f"held-out test accuracy. Seed {RANDOM_STATE}.", "",
             "Generated by `python scripts/run_ablations.py`.", "",
             "| Variant | Features | Random split | Speaker-independent | Gap |",
             "|---|---:|---:|---:|---:|"]
    for r in rows:
        lines.append(f"| {r['variant']} | {r['n_features']} | "
                     f"{r['random_accuracy']:.2%} | {r['speaker_accuracy']:.2%} | "
                     f"{r['gap_pp']:.1f} pp |")
    (REPO_ROOT / "reports" / "ablations.md").write_text("\n".join(lines) + "\n")
    print(f"\nWrote reports/ablations.md and reports/ablations.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
